#############################################################################
# Makefile for building: ui-sandbox
# Generated by qmake (3.1) (Qt 5.15.13)
# Project:  ui-sandbox.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o ui-sandbox.mk ui-sandbox.pro
#############################################################################

MAKEFILE      = ui-sandbox.mk

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++1y -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ui-sandbox1.0.0
DISTDIR = /home/rolo/work/nstl/cpp_ui_lib/.tmp/ui-sandbox1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = graphcontainer.cpp \
		graphengine.cpp \
		graphlayout.cpp \
		graphtype.cpp \
		main.cpp \
		mainwindow.cpp \
		tacticalsolutionview.cpp \
		timelinedrawingobjects.cpp \
		timelineview.cpp \
		timeselectionvisualizer.cpp \
		twoaxisdata.cpp \
		twoaxisgraph.cpp \
		waterfalldata.cpp \
		waterfallgraph.cpp \
		drawutils.cpp \
		zoompanel.cpp \
		bdwgraph.cpp \
		brwgraph.cpp \
		btwgraph.cpp \
		fdwgraph.cpp \
		ftwgraph.cpp \
		ltwgraph.cpp \
		rtwgraph.cpp \
		rtwsymboldrawing.cpp \
		btwsymboldrawing.cpp \
		simulator.cpp \
		interactivegraphicsitem.cpp \
		btwinteractiveoverlay.cpp \
		navtimeutils.cpp \
		scwwindow.cpp \
		scwsimulator.cpp \
		manoeuvreoverlay.cpp \
		debugutils.cpp \
		sharedcachestore.cpp \
		scopebus.cpp moc_graphcontainer.cpp \
		moc_graphengine.cpp \
		moc_graphlayout.cpp \
		moc_mainwindow.cpp \
		moc_tacticalsolutionview.cpp \
		moc_timelineview.cpp \
		moc_timeselectionvisualizer.cpp \
		moc_twoaxisgraph.cpp \
		moc_waterfallgraph.cpp \
		moc_zoompanel.cpp \
		moc_bdwgraph.cpp \
		moc_brwgraph.cpp \
		moc_btwgraph.cpp \
		moc_fdwgraph.cpp \
		moc_ftwgraph.cpp \
		moc_ltwgraph.cpp \
		moc_rtwgraph.cpp \
		moc_simulator.cpp \
		moc_interactivegraphicsitem.cpp \
		moc_btwinteractiveoverlay.cpp \
		moc_scwwindow.cpp \
		moc_scwsimulator.cpp \
		moc_manoeuvreoverlay.cpp \
		moc_scopebus.cpp
OBJECTS       = graphcontainer.o \
		graphengine.o \
		graphlayout.o \
		graphtype.o \
		main.o \
		mainwindow.o \
		tacticalsolutionview.o \
		timelinedrawingobjects.o \
		timelineview.o \
		timeselectionvisualizer.o \
		twoaxisdata.o \
		twoaxisgraph.o \
		waterfalldata.o \
		waterfallgraph.o \
		drawutils.o \
		zoompanel.o \
		bdwgraph.o \
		brwgraph.o \
		btwgraph.o \
		fdwgraph.o \
		ftwgraph.o \
		ltwgraph.o \
		rtwgraph.o \
		rtwsymboldrawing.o \
		btwsymboldrawing.o \
		simulator.o \
		interactivegraphicsitem.o \
		btwinteractiveoverlay.o \
		navtimeutils.o \
		scwwindow.o \
		scwsimulator.o \
		manoeuvreoverlay.o \
		debugutils.o \
		sharedcachestore.o \
		scopebus.o \
		moc_graphcontainer.o \
		moc_graphengine.o \
		moc_graphlayout.o \
		moc_mainwindow.o \
		moc_tacticalsolutionview.o \
		moc_timelineview.o \
		moc_timeselectionvisualizer.o \
		moc_twoaxisgraph.o \
		moc_waterfallgraph.o \
		moc_zoompanel.o \
		moc_bdwgraph.o \
		moc_brwgraph.o \
		moc_btwgraph.o \
		moc_fdwgraph.o \
		moc_ftwgraph.o \
		moc_ltwgraph.o \
		moc_rtwgraph.o \
		moc_simulator.o \
		moc_interactivegraphicsitem.o \
		moc_btwinteractiveoverlay.o \
		moc_scwwindow.o \
		moc_scwsimulator.o \
		moc_manoeuvreoverlay.o \
		moc_scopebus.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		ui-sandbox.pro graphcontainer.h \
		graphengine.h \
		graphlayout.h \
		graphtype.h \
		mainwindow.h \
		tacticalsolutionview.h \
		timelinedrawingobjects.h \
		timelineview.h \
		timeselectionvisualizer.h \
		twoaxisdata.h \
		twoaxisgraph.h \
		waterfalldata.h \
		waterfallgraph.h \
		drawutils.h \
		zoompanel.h \
		bdwgraph.h \
		brwgraph.h \
		btwgraph.h \
		fdwgraph.h \
		ftwgraph.h \
		ltwgraph.h \
		rtwgraph.h \
		rtwsymboldrawing.h \
		btwsymboldrawing.h \
		simulator.h \
		interactivegraphicsitem.h \
		btwinteractiveoverlay.h \
		navtimeutils.h \
		scwwindow.h \
		scwsimulator.h \
		manoeuvreoverlay.h \
		debugutils.h \
		rendercommands.h \
		sharedcachestore.h \
		scopebus.h graphcontainer.cpp \
		graphengine.cpp \
		graphlayout.cpp \
		graphtype.cpp \
		main.cpp \
		mainwindow.cpp \
		tacticalsolutionview.cpp \
		timelinedrawingobjects.cpp \
		timelineview.cpp \
		timeselectionvisualizer.cpp \
		twoaxisdata.cpp \
		twoaxisgraph.cpp \
		waterfalldata.cpp \
		waterfallgraph.cpp \
		drawutils.cpp \
		zoompanel.cpp \
		bdwgraph.cpp \
		brwgraph.cpp \
		btwgraph.cpp \
		fdwgraph.cpp \
		ftwgraph.cpp \
		ltwgraph.cpp \
		rtwgraph.cpp \
		rtwsymboldrawing.cpp \
		btwsymboldrawing.cpp \
		simulator.cpp \
		interactivegraphicsitem.cpp \
		btwinteractiveoverlay.cpp \
		navtimeutils.cpp \
		scwwindow.cpp \
		scwsimulator.cpp \
		manoeuvreoverlay.cpp \
		debugutils.cpp \
		sharedcachestore.cpp \
		scopebus.cpp
QMAKE_TARGET  = ui-sandbox
DESTDIR       = 
TARGET        = ui-sandbox


first: all
####### Build rules

ui-sandbox: ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

ui-sandbox.mk: ui-sandbox.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		ui-sandbox.pro
	$(QMAKE) -o ui-sandbox.mk ui-sandbox.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
ui-sandbox.pro:
qmake: FORCE
	@$(QMAKE) -o ui-sandbox.mk ui-sandbox.pro

qmake_all: FORCE


all: ui-sandbox.mk ui-sandbox

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents graphcontainer.h graphengine.h graphlayout.h graphtype.h mainwindow.h tacticalsolutionview.h timelinedrawingobjects.h timelineview.h timeselectionvisualizer.h twoaxisdata.h twoaxisgraph.h waterfalldata.h waterfallgraph.h drawutils.h zoompanel.h bdwgraph.h brwgraph.h btwgraph.h fdwgraph.h ftwgraph.h ltwgraph.h rtwgraph.h rtwsymboldrawing.h btwsymboldrawing.h simulator.h interactivegraphicsitem.h btwinteractiveoverlay.h navtimeutils.h scwwindow.h scwsimulator.h manoeuvreoverlay.h debugutils.h rendercommands.h sharedcachestore.h scopebus.h $(DISTDIR)/
	$(COPY_FILE) --parents graphcontainer.cpp graphengine.cpp graphlayout.cpp graphtype.cpp main.cpp mainwindow.cpp tacticalsolutionview.cpp timelinedrawingobjects.cpp timelineview.cpp timeselectionvisualizer.cpp twoaxisdata.cpp twoaxisgraph.cpp waterfalldata.cpp waterfallgraph.cpp drawutils.cpp zoompanel.cpp bdwgraph.cpp brwgraph.cpp btwgraph.cpp fdwgraph.cpp ftwgraph.cpp ltwgraph.cpp rtwgraph.cpp rtwsymboldrawing.cpp btwsymboldrawing.cpp simulator.cpp interactivegraphicsitem.cpp btwinteractiveoverlay.cpp navtimeutils.cpp scwwindow.cpp scwsimulator.cpp manoeuvreoverlay.cpp debugutils.cpp sharedcachestore.cpp scopebus.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) ui-sandbox.mk


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -std=gnu++1y -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_graphcontainer.cpp moc_graphengine.cpp moc_graphlayout.cpp moc_mainwindow.cpp moc_tacticalsolutionview.cpp moc_timelineview.cpp moc_timeselectionvisualizer.cpp moc_twoaxisgraph.cpp moc_waterfallgraph.cpp moc_zoompanel.cpp moc_bdwgraph.cpp moc_brwgraph.cpp moc_btwgraph.cpp moc_fdwgraph.cpp moc_ftwgraph.cpp moc_ltwgraph.cpp moc_rtwgraph.cpp moc_simulator.cpp moc_interactivegraphicsitem.cpp moc_btwinteractiveoverlay.cpp moc_scwwindow.cpp moc_scwsimulator.cpp moc_manoeuvreoverlay.cpp moc_scopebus.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_graphcontainer.cpp moc_graphengine.cpp moc_graphlayout.cpp moc_mainwindow.cpp moc_tacticalsolutionview.cpp moc_timelineview.cpp moc_timeselectionvisualizer.cpp moc_twoaxisgraph.cpp moc_waterfallgraph.cpp moc_zoompanel.cpp moc_bdwgraph.cpp moc_brwgraph.cpp moc_btwgraph.cpp moc_fdwgraph.cpp moc_ftwgraph.cpp moc_ltwgraph.cpp moc_rtwgraph.cpp moc_simulator.cpp moc_interactivegraphicsitem.cpp moc_btwinteractiveoverlay.cpp moc_scwwindow.cpp moc_scwsimulator.cpp moc_manoeuvreoverlay.cpp moc_scopebus.cpp
moc_graphcontainer.cpp: graphcontainer.h \
		bdwgraph.h \
		waterfallgraph.h \
		drawutils.h \
		timelineutils.h \
		waterfalldata.h \
		circularbuffer.h \
		btwsymboldrawing.h \
		sharedsyncstate.h \
		rendercommands.h \
		brwgraph.h \
		btwgraph.h \
		rulerstate.h \
		fdwgraph.h \
		ftwgraph.h \
		graphtype.h \
		ltwgraph.h \
		rtwgraph.h \
		rtwsymboldrawing.h \
		timelineview.h \
		timelinedrawingobjects.h \
		manoeuvreoverlay.h \
		timeselectionvisualizer.h \
		zoompanel.h \
		scopebus.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rolo/work/nstl/cpp_ui_lib/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rolo/work/nstl/cpp_ui_lib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include graphcontainer.h -o moc_graphcontainer.cpp

moc_graphengine.cpp: graphengine.h \
		waterfalldata.h \
		circularbuffer.h \
		btwsymboldrawing.h \
		graphtype.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rolo/work/nstl/cpp_ui_lib/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rolo/work/nstl/cpp_ui_lib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include graphengine.h -o moc_graphengine.cpp

moc_graphlayout.cpp: graphlayout.h \
		graphcontainer.h \
		bdwgraph.h \
		waterfallgraph.h \
		drawutils.h \
		timelineutils.h \
		waterfalldata.h \
		circularbuffer.h \
		btwsymboldrawing.h \
		sharedsyncstate.h \
		rendercommands.h \
		brwgraph.h \
		btwgraph.h \
		rulerstate.h \
		fdwgraph.h \
		ftwgraph.h \
		graphtype.h \
		ltwgraph.h \
		rtwgraph.h \
		rtwsymboldrawing.h \
		timelineview.h \
		timelinedrawingobjects.h \
		manoeuvreoverlay.h \
		timeselectionvisualizer.h \
		zoompanel.h \
		scopebus.h \
		graphengine.h \
		sharedcachestore.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rolo/work/nstl/cpp_ui_lib/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rolo/work/nstl/cpp_ui_lib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include graphlayout.h -o moc_graphlayout.cpp

moc_mainwindow.cpp: mainwindow.h \
		bdwgraph.h \
		waterfallgraph.h \
		drawutils.h \
		timelineutils.h \
		waterfalldata.h \
		circularbuffer.h \
		btwsymboldrawing.h \
		sharedsyncstate.h \
		rendercommands.h \
		brwgraph.h \
		btwgraph.h \
		rulerstate.h \
		fdwgraph.h \
		ftwgraph.h \
		graphcontainer.h \
		graphtype.h \
		ltwgraph.h \
		rtwgraph.h \
		rtwsymboldrawing.h \
		timelineview.h \
		timelinedrawingobjects.h \
		manoeuvreoverlay.h \
		timeselectionvisualizer.h \
		zoompanel.h \
		scopebus.h \
		graphlayout.h \
		graphengine.h \
		sharedcachestore.h \
		simulator.h \
		scwwindow.h \
		scwsimulator.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rolo/work/nstl/cpp_ui_lib/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rolo/work/nstl/cpp_ui_lib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_tacticalsolutionview.cpp: tacticalsolutionview.h \
		drawutils.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rolo/work/nstl/cpp_ui_lib/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rolo/work/nstl/cpp_ui_lib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include tacticalsolutionview.h -o moc_tacticalsolutionview.cpp

moc_timelineview.cpp: timelineview.h \
		timelineutils.h \
		timelinedrawingobjects.h \
		sharedsyncstate.h \
		manoeuvreoverlay.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rolo/work/nstl/cpp_ui_lib/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rolo/work/nstl/cpp_ui_lib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include timelineview.h -o moc_timelineview.cpp

moc_timeselectionvisualizer.cpp: timeselectionvisualizer.h \
		timelineutils.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rolo/work/nstl/cpp_ui_lib/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rolo/work/nstl/cpp_ui_lib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include timeselectionvisualizer.h -o moc_timeselectionvisualizer.cpp

moc_twoaxisgraph.cpp: twoaxisgraph.h \
		twoaxisdata.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rolo/work/nstl/cpp_ui_lib/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rolo/work/nstl/cpp_ui_lib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include twoaxisgraph.h -o moc_twoaxisgraph.cpp

moc_waterfallgraph.cpp: waterfallgraph.h \
		drawutils.h \
		timelineutils.h \
		waterfalldata.h \
		circularbuffer.h \
		btwsymboldrawing.h \
		sharedsyncstate.h \
		rendercommands.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rolo/work/nstl/cpp_ui_lib/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rolo/work/nstl/cpp_ui_lib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include waterfallgraph.h -o moc_waterfallgraph.cpp

moc_zoompanel.cpp: zoompanel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rolo/work/nstl/cpp_ui_lib/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rolo/work/nstl/cpp_ui_lib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include zoompanel.h -o moc_zoompanel.cpp

moc_bdwgraph.cpp: bdwgraph.h \
		waterfallgraph.h \
		drawutils.h \
		timelineutils.h \
		waterfalldata.h \
		circularbuffer.h \
		btwsymboldrawing.h \
		sharedsyncstate.h \
		rendercommands.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rolo/work/nstl/cpp_ui_lib/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rolo/work/nstl/cpp_ui_lib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include bdwgraph.h -o moc_bdwgraph.cpp

moc_brwgraph.cpp: brwgraph.h \
		waterfallgraph.h \
		drawutils.h \
		timelineutils.h \
		waterfalldata.h \
		circularbuffer.h \
		btwsymboldrawing.h \
		sharedsyncstate.h \
		rendercommands.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rolo/work/nstl/cpp_ui_lib/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rolo/work/nstl/cpp_ui_lib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include brwgraph.h -o moc_brwgraph.cpp

moc_btwgraph.cpp: btwgraph.h \
		waterfallgraph.h \
		drawutils.h \
		timelineutils.h \
		waterfalldata.h \
		circularbuffer.h \
		btwsymboldrawing.h \
		sharedsyncstate.h \
		rendercommands.h \
		rulerstate.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rolo/work/nstl/cpp_ui_lib/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rolo/work/nstl/cpp_ui_lib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include btwgraph.h -o moc_btwgraph.cpp

moc_fdwgraph.cpp: fdwgraph.h \
		waterfallgraph.h \
		drawutils.h \
		timelineutils.h \
		waterfalldata.h \
		circularbuffer.h \
		btwsymboldrawing.h \
		sharedsyncstate.h \
		rendercommands.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rolo/work/nstl/cpp_ui_lib/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rolo/work/nstl/cpp_ui_lib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include fdwgraph.h -o moc_fdwgraph.cpp

moc_ftwgraph.cpp: ftwgraph.h \
		waterfallgraph.h \
		drawutils.h \
		timelineutils.h \
		waterfalldata.h \
		circularbuffer.h \
		btwsymboldrawing.h \
		sharedsyncstate.h \
		rendercommands.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rolo/work/nstl/cpp_ui_lib/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rolo/work/nstl/cpp_ui_lib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ftwgraph.h -o moc_ftwgraph.cpp

moc_ltwgraph.cpp: ltwgraph.h \
		waterfallgraph.h \
		drawutils.h \
		timelineutils.h \
		waterfalldata.h \
		circularbuffer.h \
		btwsymboldrawing.h \
		sharedsyncstate.h \
		rendercommands.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rolo/work/nstl/cpp_ui_lib/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rolo/work/nstl/cpp_ui_lib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ltwgraph.h -o moc_ltwgraph.cpp

moc_rtwgraph.cpp: rtwgraph.h \
		waterfallgraph.h \
		drawutils.h \
		timelineutils.h \
		waterfalldata.h \
		circularbuffer.h \
		btwsymboldrawing.h \
		sharedsyncstate.h \
		rendercommands.h \
		rtwsymboldrawing.h \
		rulerstate.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rolo/work/nstl/cpp_ui_lib/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rolo/work/nstl/cpp_ui_lib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include rtwgraph.h -o moc_rtwgraph.cpp

moc_simulator.cpp: simulator.h \
		graphlayout.h \
		graphcontainer.h \
		bdwgraph.h \
		waterfallgraph.h \
		drawutils.h \
		timelineutils.h \
		waterfalldata.h \
		circularbuffer.h \
		btwsymboldrawing.h \
		sharedsyncstate.h \
		rendercommands.h \
		brwgraph.h \
		btwgraph.h \
		rulerstate.h \
		fdwgraph.h \
		ftwgraph.h \
		graphtype.h \
		ltwgraph.h \
		rtwgraph.h \
		rtwsymboldrawing.h \
		timelineview.h \
		timelinedrawingobjects.h \
		manoeuvreoverlay.h \
		timeselectionvisualizer.h \
		zoompanel.h \
		scopebus.h \
		graphengine.h \
		sharedcachestore.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rolo/work/nstl/cpp_ui_lib/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rolo/work/nstl/cpp_ui_lib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include simulator.h -o moc_simulator.cpp

moc_interactivegraphicsitem.cpp: interactivegraphicsitem.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rolo/work/nstl/cpp_ui_lib/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rolo/work/nstl/cpp_ui_lib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include interactivegraphicsitem.h -o moc_interactivegraphicsitem.cpp

moc_btwinteractiveoverlay.cpp: btwinteractiveoverlay.h \
		interactivegraphicsitem.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rolo/work/nstl/cpp_ui_lib/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rolo/work/nstl/cpp_ui_lib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include btwinteractiveoverlay.h -o moc_btwinteractiveoverlay.cpp

moc_scwwindow.cpp: scwwindow.h \
		timelineview.h \
		timelineutils.h \
		timelinedrawingobjects.h \
		sharedsyncstate.h \
		manoeuvreoverlay.h \
		waterfalldata.h \
		circularbuffer.h \
		waterfallgraph.h \
		drawutils.h \
		btwsymboldrawing.h \
		rendercommands.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rolo/work/nstl/cpp_ui_lib/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rolo/work/nstl/cpp_ui_lib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include scwwindow.h -o moc_scwwindow.cpp

moc_scwsimulator.cpp: scwsimulator.h \
		scwwindow.h \
		timelineview.h \
		timelineutils.h \
		timelinedrawingobjects.h \
		sharedsyncstate.h \
		manoeuvreoverlay.h \
		waterfalldata.h \
		circularbuffer.h \
		waterfallgraph.h \
		drawutils.h \
		btwsymboldrawing.h \
		rendercommands.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rolo/work/nstl/cpp_ui_lib/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rolo/work/nstl/cpp_ui_lib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include scwsimulator.h -o moc_scwsimulator.cpp

moc_manoeuvreoverlay.cpp: manoeuvreoverlay.h \
		timelineutils.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rolo/work/nstl/cpp_ui_lib/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rolo/work/nstl/cpp_ui_lib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include manoeuvreoverlay.h -o moc_manoeuvreoverlay.cpp

moc_scopebus.cpp: scopebus.h \
		timelineutils.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rolo/work/nstl/cpp_ui_lib/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rolo/work/nstl/cpp_ui_lib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include scopebus.h -o moc_scopebus.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		/usr/lib/qt5/bin/uic \
		twoaxisgraph.h \
		tacticalsolutionview.h \
		graphcontainer.h \
		zoompanel.h \
		twoaxisdata.h \
		drawutils.h \
		bdwgraph.h \
		waterfallgraph.h \
		drawutils.h \
		timelineutils.h \
		waterfalldata.h \
		circularbuffer.h \
		btwsymboldrawing.h \
		sharedsyncstate.h \
		rendercommands.h \
		brwgraph.h \
		btwgraph.h \
		rulerstate.h \
		fdwgraph.h \
		ftwgraph.h \
		graphtype.h \
		ltwgraph.h \
		rtwgraph.h \
		rtwsymboldrawing.h \
		timelineview.h \
		timelinedrawingobjects.h \
		manoeuvreoverlay.h \
		timeselectionvisualizer.h \
		zoompanel.h \
		scopebus.h
	/usr/lib/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

graphcontainer.o: graphcontainer.cpp graphcontainer.h \
		bdwgraph.h \
		waterfallgraph.h \
		drawutils.h \
		timelineutils.h \
		waterfalldata.h \
		circularbuffer.h \
		btwsymboldrawing.h \
		sharedsyncstate.h \
		rendercommands.h \
		brwgraph.h \
		btwgraph.h \
		rulerstate.h \
		fdwgraph.h \
		ftwgraph.h \
		graphtype.h \
		ltwgraph.h \
		rtwgraph.h \
		rtwsymboldrawing.h \
		timelineview.h \
		timelinedrawingobjects.h \
		manoeuvreoverlay.h \
		timeselectionvisualizer.h \
		zoompanel.h \
		scopebus.h \
		graphlayout.h \
		graphengine.h \
		sharedcachestore.h \
		btwinteractiveoverlay.h \
		interactivegraphicsitem.h \
		debugutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphcontainer.o graphcontainer.cpp

graphengine.o: graphengine.cpp graphengine.h \
		waterfalldata.h \
		circularbuffer.h \
		btwsymboldrawing.h \
		graphtype.h \
		debugutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphengine.o graphengine.cpp

graphlayout.o: graphlayout.cpp graphlayout.h \
		graphcontainer.h \
		bdwgraph.h \
		waterfallgraph.h \
		drawutils.h \
		timelineutils.h \
		waterfalldata.h \
		circularbuffer.h \
		btwsymboldrawing.h \
		sharedsyncstate.h \
		rendercommands.h \
		brwgraph.h \
		btwgraph.h \
		rulerstate.h \
		fdwgraph.h \
		ftwgraph.h \
		graphtype.h \
		ltwgraph.h \
		rtwgraph.h \
		rtwsymboldrawing.h \
		timelineview.h \
		timelinedrawingobjects.h \
		manoeuvreoverlay.h \
		timeselectionvisualizer.h \
		zoompanel.h \
		scopebus.h \
		graphengine.h \
		sharedcachestore.h \
		navtimeutils.h \
		btwinteractiveoverlay.h \
		interactivegraphicsitem.h \
		debugutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphlayout.o graphlayout.cpp

graphtype.o: graphtype.cpp graphtype.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphtype.o graphtype.cpp

main.o: main.cpp mainwindow.h \
		bdwgraph.h \
		waterfallgraph.h \
		drawutils.h \
		timelineutils.h \
		waterfalldata.h \
		circularbuffer.h \
		btwsymboldrawing.h \
		sharedsyncstate.h \
		rendercommands.h \
		brwgraph.h \
		btwgraph.h \
		rulerstate.h \
		fdwgraph.h \
		ftwgraph.h \
		graphcontainer.h \
		graphtype.h \
		ltwgraph.h \
		rtwgraph.h \
		rtwsymboldrawing.h \
		timelineview.h \
		timelinedrawingobjects.h \
		manoeuvreoverlay.h \
		timeselectionvisualizer.h \
		zoompanel.h \
		scopebus.h \
		graphlayout.h \
		graphengine.h \
		sharedcachestore.h \
		simulator.h \
		scwwindow.h \
		scwsimulator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		bdwgraph.h \
		waterfallgraph.h \
		drawutils.h \
		timelineutils.h \
		waterfalldata.h \
		circularbuffer.h \
		btwsymboldrawing.h \
		sharedsyncstate.h \
		rendercommands.h \
		brwgraph.h \
		btwgraph.h \
		rulerstate.h \
		fdwgraph.h \
		ftwgraph.h \
		graphcontainer.h \
		graphtype.h \
		ltwgraph.h \
		rtwgraph.h \
		rtwsymboldrawing.h \
		timelineview.h \
		timelinedrawingobjects.h \
		manoeuvreoverlay.h \
		timeselectionvisualizer.h \
		zoompanel.h \
		scopebus.h \
		graphlayout.h \
		graphengine.h \
		sharedcachestore.h \
		simulator.h \
		scwwindow.h \
		scwsimulator.h \
		ui_mainwindow.h \
		tacticalsolutionview.h \
		twoaxisgraph.h \
		twoaxisdata.h \
		debugutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

tacticalsolutionview.o: tacticalsolutionview.cpp tacticalsolutionview.h \
		drawutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tacticalsolutionview.o tacticalsolutionview.cpp

timelinedrawingobjects.o: timelinedrawingobjects.cpp timelinedrawingobjects.h \
		timelineutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o timelinedrawingobjects.o timelinedrawingobjects.cpp

timelineview.o: timelineview.cpp timelineview.h \
		timelineutils.h \
		timelinedrawingobjects.h \
		sharedsyncstate.h \
		manoeuvreoverlay.h \
		navtimeutils.h \
		debugutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o timelineview.o timelineview.cpp

timeselectionvisualizer.o: timeselectionvisualizer.cpp timeselectionvisualizer.h \
		timelineutils.h \
		debugutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o timeselectionvisualizer.o timeselectionvisualizer.cpp

twoaxisdata.o: twoaxisdata.cpp twoaxisdata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o twoaxisdata.o twoaxisdata.cpp

twoaxisgraph.o: twoaxisgraph.cpp twoaxisgraph.h \
		twoaxisdata.h \
		debugutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o twoaxisgraph.o twoaxisgraph.cpp

waterfalldata.o: waterfalldata.cpp waterfalldata.h \
		circularbuffer.h \
		btwsymboldrawing.h \
		debugutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o waterfalldata.o waterfalldata.cpp

waterfallgraph.o: waterfallgraph.cpp waterfallgraph.h \
		drawutils.h \
		timelineutils.h \
		waterfalldata.h \
		circularbuffer.h \
		btwsymboldrawing.h \
		sharedsyncstate.h \
		rendercommands.h \
		graphengine.h \
		graphtype.h \
		sharedcachestore.h \
		debugutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o waterfallgraph.o waterfallgraph.cpp

drawutils.o: drawutils.cpp drawutils.h \
		debugutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o drawutils.o drawutils.cpp

zoompanel.o: zoompanel.cpp zoompanel.h \
		debugutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zoompanel.o zoompanel.cpp

bdwgraph.o: bdwgraph.cpp bdwgraph.h \
		waterfallgraph.h \
		drawutils.h \
		timelineutils.h \
		waterfalldata.h \
		circularbuffer.h \
		btwsymboldrawing.h \
		sharedsyncstate.h \
		rendercommands.h \
		debugutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bdwgraph.o bdwgraph.cpp

brwgraph.o: brwgraph.cpp brwgraph.h \
		waterfallgraph.h \
		drawutils.h \
		timelineutils.h \
		waterfalldata.h \
		circularbuffer.h \
		btwsymboldrawing.h \
		sharedsyncstate.h \
		rendercommands.h \
		debugutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o brwgraph.o brwgraph.cpp

btwgraph.o: btwgraph.cpp btwgraph.h \
		waterfallgraph.h \
		drawutils.h \
		timelineutils.h \
		waterfalldata.h \
		circularbuffer.h \
		btwsymboldrawing.h \
		sharedsyncstate.h \
		rendercommands.h \
		rulerstate.h \
		btwinteractiveoverlay.h \
		interactivegraphicsitem.h \
		graphcontainer.h \
		bdwgraph.h \
		brwgraph.h \
		fdwgraph.h \
		ftwgraph.h \
		graphtype.h \
		ltwgraph.h \
		rtwgraph.h \
		rtwsymboldrawing.h \
		timelineview.h \
		timelinedrawingobjects.h \
		manoeuvreoverlay.h \
		timeselectionvisualizer.h \
		zoompanel.h \
		scopebus.h \
		graphlayout.h \
		graphengine.h \
		sharedcachestore.h \
		debugutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o btwgraph.o btwgraph.cpp

fdwgraph.o: fdwgraph.cpp fdwgraph.h \
		waterfallgraph.h \
		drawutils.h \
		timelineutils.h \
		waterfalldata.h \
		circularbuffer.h \
		btwsymboldrawing.h \
		sharedsyncstate.h \
		rendercommands.h \
		debugutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fdwgraph.o fdwgraph.cpp

ftwgraph.o: ftwgraph.cpp ftwgraph.h \
		waterfallgraph.h \
		drawutils.h \
		timelineutils.h \
		waterfalldata.h \
		circularbuffer.h \
		btwsymboldrawing.h \
		sharedsyncstate.h \
		rendercommands.h \
		debugutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ftwgraph.o ftwgraph.cpp

ltwgraph.o: ltwgraph.cpp ltwgraph.h \
		waterfallgraph.h \
		drawutils.h \
		timelineutils.h \
		waterfalldata.h \
		circularbuffer.h \
		btwsymboldrawing.h \
		sharedsyncstate.h \
		rendercommands.h \
		debugutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ltwgraph.o ltwgraph.cpp

rtwgraph.o: rtwgraph.cpp rtwgraph.h \
		waterfallgraph.h \
		drawutils.h \
		timelineutils.h \
		waterfalldata.h \
		circularbuffer.h \
		btwsymboldrawing.h \
		sharedsyncstate.h \
		rendercommands.h \
		rtwsymboldrawing.h \
		rulerstate.h \
		debugutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rtwgraph.o rtwgraph.cpp

rtwsymboldrawing.o: rtwsymboldrawing.cpp rtwsymboldrawing.h \
		debugutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rtwsymboldrawing.o rtwsymboldrawing.cpp

btwsymboldrawing.o: btwsymboldrawing.cpp btwsymboldrawing.h \
		debugutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o btwsymboldrawing.o btwsymboldrawing.cpp

simulator.o: simulator.cpp simulator.h \
		graphlayout.h \
		graphcontainer.h \
		bdwgraph.h \
		waterfallgraph.h \
		drawutils.h \
		timelineutils.h \
		waterfalldata.h \
		circularbuffer.h \
		btwsymboldrawing.h \
		sharedsyncstate.h \
		rendercommands.h \
		brwgraph.h \
		btwgraph.h \
		rulerstate.h \
		fdwgraph.h \
		ftwgraph.h \
		graphtype.h \
		ltwgraph.h \
		rtwgraph.h \
		rtwsymboldrawing.h \
		timelineview.h \
		timelinedrawingobjects.h \
		manoeuvreoverlay.h \
		timeselectionvisualizer.h \
		zoompanel.h \
		scopebus.h \
		graphengine.h \
		sharedcachestore.h \
		debugutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o simulator.o simulator.cpp

interactivegraphicsitem.o: interactivegraphicsitem.cpp interactivegraphicsitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o interactivegraphicsitem.o interactivegraphicsitem.cpp

btwinteractiveoverlay.o: btwinteractiveoverlay.cpp btwinteractiveoverlay.h \
		interactivegraphicsitem.h \
		btwgraph.h \
		waterfallgraph.h \
		drawutils.h \
		timelineutils.h \
		waterfalldata.h \
		circularbuffer.h \
		btwsymboldrawing.h \
		sharedsyncstate.h \
		rendercommands.h \
		rulerstate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o btwinteractiveoverlay.o btwinteractiveoverlay.cpp

navtimeutils.o: navtimeutils.cpp navtimeutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o navtimeutils.o navtimeutils.cpp

scwwindow.o: scwwindow.cpp scwwindow.h \
		timelineview.h \
		timelineutils.h \
		timelinedrawingobjects.h \
		sharedsyncstate.h \
		manoeuvreoverlay.h \
		waterfalldata.h \
		circularbuffer.h \
		waterfallgraph.h \
		drawutils.h \
		btwsymboldrawing.h \
		rendercommands.h \
		debugutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scwwindow.o scwwindow.cpp

scwsimulator.o: scwsimulator.cpp scwsimulator.h \
		scwwindow.h \
		timelineview.h \
		timelineutils.h \
		timelinedrawingobjects.h \
		sharedsyncstate.h \
		manoeuvreoverlay.h \
		waterfalldata.h \
		circularbuffer.h \
		waterfallgraph.h \
		drawutils.h \
		btwsymboldrawing.h \
		rendercommands.h \
		debugutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scwsimulator.o scwsimulator.cpp

manoeuvreoverlay.o: manoeuvreoverlay.cpp manoeuvreoverlay.h \
		timelineutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o manoeuvreoverlay.o manoeuvreoverlay.cpp

debugutils.o: debugutils.cpp debugutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debugutils.o debugutils.cpp

sharedcachestore.o: sharedcachestore.cpp sharedcachestore.h \
		circularbuffer.h \
		graphtype.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sharedcachestore.o sharedcachestore.cpp

scopebus.o: scopebus.cpp scopebus.h \
		timelineutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scopebus.o scopebus.cpp

moc_graphcontainer.o: moc_graphcontainer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_graphcontainer.o moc_graphcontainer.cpp

moc_graphengine.o: moc_graphengine.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_graphengine.o moc_graphengine.cpp

moc_graphlayout.o: moc_graphlayout.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_graphlayout.o moc_graphlayout.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_tacticalsolutionview.o: moc_tacticalsolutionview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tacticalsolutionview.o moc_tacticalsolutionview.cpp

moc_timelineview.o: moc_timelineview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_timelineview.o moc_timelineview.cpp

moc_timeselectionvisualizer.o: moc_timeselectionvisualizer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_timeselectionvisualizer.o moc_timeselectionvisualizer.cpp

moc_twoaxisgraph.o: moc_twoaxisgraph.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_twoaxisgraph.o moc_twoaxisgraph.cpp

moc_waterfallgraph.o: moc_waterfallgraph.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_waterfallgraph.o moc_waterfallgraph.cpp

moc_zoompanel.o: moc_zoompanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_zoompanel.o moc_zoompanel.cpp

moc_bdwgraph.o: moc_bdwgraph.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_bdwgraph.o moc_bdwgraph.cpp

moc_brwgraph.o: moc_brwgraph.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_brwgraph.o moc_brwgraph.cpp

moc_btwgraph.o: moc_btwgraph.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_btwgraph.o moc_btwgraph.cpp

moc_fdwgraph.o: moc_fdwgraph.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fdwgraph.o moc_fdwgraph.cpp

moc_ftwgraph.o: moc_ftwgraph.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ftwgraph.o moc_ftwgraph.cpp

moc_ltwgraph.o: moc_ltwgraph.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ltwgraph.o moc_ltwgraph.cpp

moc_rtwgraph.o: moc_rtwgraph.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rtwgraph.o moc_rtwgraph.cpp

moc_simulator.o: moc_simulator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_simulator.o moc_simulator.cpp

moc_interactivegraphicsitem.o: moc_interactivegraphicsitem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_interactivegraphicsitem.o moc_interactivegraphicsitem.cpp

moc_btwinteractiveoverlay.o: moc_btwinteractiveoverlay.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_btwinteractiveoverlay.o moc_btwinteractiveoverlay.cpp

moc_scwwindow.o: moc_scwwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_scwwindow.o moc_scwwindow.cpp

moc_scwsimulator.o: moc_scwsimulator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_scwsimulator.o moc_scwsimulator.cpp

moc_manoeuvreoverlay.o: moc_manoeuvreoverlay.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_manoeuvreoverlay.o moc_manoeuvreoverlay.cpp

moc_scopebus.o: moc_scopebus.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_scopebus.o moc_scopebus.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/ui-sandbox/bin || mkdir -p $(INSTALL_ROOT)/opt/ui-sandbox/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/ui-sandbox/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/ui-sandbox/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/ui-sandbox/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

